### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by AlexKucera** [ericdke/apero-docs#1]
Hi Eric,

with the latest release 1.3.1 (7) I get instant crashes on launch. Here is a Gist with the crash report. Maybe it helps.

https://gist.github.com/AlexKucera/c8dafeff80e928f35dc7f41aa4f2f8ee

**Comment by ericdke** [comment]
Hi, thank you for your feedback. I'm so sorry about this crash. Looks like I introduced a bug with the last revision. I will submit a fix to the App Store asap, probably tomorrow. I'll let you know. Thanks again for this report. And sorry for the inconvenience. :/

-- 
Eric Dejonckheere

**Comment by AlexKucera** [comment]
No problem. It happens. I'm looking forward to the fixed build.

**Comment by ericdke** [comment]
I see what happened. This is an issue with macOS 10.11 and the new login window - unfortunately I don't have a 10.11 machine to run tests at home, only a 10.12 one... and of course, boom, something is not compatible anymore. I will either revert to the previous implementation, or find a way to make this new one compatible for both OS versions. Thank you for your patience. :)

**Comment by AlexKucera** [comment]
Feel free to send me test builds to verify the fix.

**Comment by ericdke** [comment]
I think I found a solution. I've sent you a PM on pnut with a link to a debug version.

**Comment by ericdke** [comment]
This build has been submitted to the Mac App Store. Thank you for your feedback, Alex! 👍
